'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { BarChart3, FilePlus2, Users, Settings, LogOut, Newspaper } from 'lucide-react';

type Session={id:string;name:string};
export default function Home(){
 const [session,setSession]=useState<Session|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('tk_user_session');if(raw)setSession(JSON.parse(raw))}catch{}} ,[]);
 if(!session)return <Login />;
 return <div className="shell"><Sidebar/><main className="content"><div className="topbar"><div><div className="eyebrow">Internal Portal</div><h1 className="title">Dashboard</h1></div><div className="user"><span>{session.name}<br/><small>{session.id}</small></span><div className="avatar">{session.name.slice(0,1)}</div></div></div><section className="hero"><div className="eyebrow" style={{color:'#ffb2b2'}}>TongerKhobor</div><h1>Welcome back, {session.name} ☕</h1><p>Your internal newsroom workspace for drafting, designing and preparing publications.</p><div className="actions"><Link className="btn primary" href="/newscard"><FilePlus2 size={17}/> Create news card</Link><Link className="btn" href="/profile">Edit profile</Link></div></section><div className="grid"><Stat icon={<Newspaper/>} title="News cards" value="—"/><Stat icon={<BarChart3/>} title="Your activity" value="—"/><Stat icon={<Users/>} title="Team" value="—"/></div><section className="panel" style={{marginTop:18}}><h3>Quick workspace</h3><p className="muted">Use the News Card Studio to prepare Bengali or English social cards. The workspace keeps the original TongerKhobor categories and black/white variants while giving the portal a cleaner, faster interface.</p><div className="actions"><Link className="btn primary" href="/newscard">Open News Card Studio</Link><Link className="btn" href="/team">View team</Link><Link className="btn" href="/admin">Admin</Link></div></section></main></div>
}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="panel"><div style={{color:'#731919'}}>{icon}</div><div className="muted">{title}</div><div className="stat">{value}</div></div>}
function Sidebar(){return <aside className="sidebar"><div className="brand">টং-এর খবর<small>INTERNAL WORKSPACE</small></div><nav className="nav"><Link className="active" href="/">Dashboard</Link><Link href="/newscard">News Card Studio</Link><Link href="/profile">Profile</Link><Link href="/team">Team</Link><Link href="/admin">Admin</Link></nav><button className="btn" style={{position:'absolute',bottom:24,left:16,right:16}} onClick={()=>{localStorage.removeItem('tk_user_session');location.href='/'}}><LogOut size={16}/> Logout</button></aside>}
function Login(){return <div className="form"><div className="eyebrow">Private access</div><h1>TongerKhobor</h1><p className="muted">Sign in to the internal newsroom workspace.</p><label className="field">Member ID<input id="id" className="input" placeholder="Your internal member ID"/></label><label className="field">Password<input id="password" className="input" type="password" placeholder="Your password"/></label><button className="btn primary" style={{width:'100%',marginTop:8}} onClick={()=>{const id=(document.getElementById('id') as HTMLInputElement).value.trim();const name=id||'Member';if(!id)return;localStorage.setItem('tk_user_session',JSON.stringify({id,name}));location.reload()}}>Authenticate session</button><div className="notice">Internal portal • TongerKhobor team only</div></div>}
