'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { BarChart3, FilePlus2, Users, LogOut, Newspaper, Loader2 } from 'lucide-react';
import { doc, getDoc } from 'firebase/firestore';
import { db } from './lib/firebase';

type Session={id:string;name:string};
export default function Home(){
 const [session,setSession]=useState<Session|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('tk_user_session');if(raw)setSession(JSON.parse(raw))}catch{}} ,[]);
 if(!session)return <Login />;
 return <div className="shell"><Sidebar/><main className="content"><div className="topbar"><div><div className="eyebrow">Internal Portal</div><h1 className="title">Dashboard</h1></div><div className="user"><span>{session.name}<br/><small>{session.id}</small></span><div className="avatar">{session.name.slice(0,1)}</div></div></div><section className="hero"><div className="eyebrow" style={{color:'#ffb2b2'}}>TongerKhobor</div><h1>Welcome back, {session.name} ☕</h1><p>Your internal newsroom workspace for drafting, designing and preparing publications.</p><div className="actions"><Link className="btn primary" href="/newscard"><FilePlus2 size={17}/> Create news card</Link><Link className="btn" href="/profile">Edit profile</Link></div></section><div className="grid"><Stat icon={<Newspaper/>} title="News cards" value="Ready"/><Stat icon={<BarChart3/>} title="Workspace" value="Active"/><Stat icon={<Users/>} title="Team" value="Connected"/></div><section className="panel" style={{marginTop:18}}><h3>Quick workspace</h3><p className="muted">Prepare Bengali or English social cards with the original TongerKhobor categories and black/white variants in a cleaner studio.</p><div className="actions"><Link className="btn primary" href="/newscard">Open News Card Studio</Link><Link className="btn" href="/team">View team</Link><Link className="btn" href="/admin">Admin</Link></div></section></main></div>
}
function Stat({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="panel"><div style={{color:'#731919'}}>{icon}</div><div className="muted">{title}</div><div className="stat">{value}</div></div>}
function Sidebar(){return <aside className="sidebar"><div className="brand">টং-এর খবর<small>INTERNAL WORKSPACE</small></div><nav className="nav"><Link className="active" href="/">Dashboard</Link><Link href="/newscard">News Card Studio</Link><Link href="/profile">Profile</Link><Link href="/team">Team</Link><Link href="/admin">Admin</Link></nav><button className="btn" style={{position:'absolute',bottom:24,left:16,right:16}} onClick={()=>{localStorage.removeItem('tk_user_session');location.href='/'}}><LogOut size={16}/> Logout</button></aside>}
function Login(){const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function signIn(){setError('');const id=(document.getElementById('id') as HTMLInputElement).value.trim();const password=(document.getElementById('password') as HTMLInputElement).value;if(!id||!password){setError('Member ID and password are required.');return}setBusy(true);try{const clean=id.toLowerCase().replace(/[^a-z0-9_-]/g,'');const snap=await getDoc(doc(db,'members',clean));if(!snap.exists()){setError('Invalid member ID or password.');return}const data=snap.data() as {name?:string;password?:string};if(data.password!==password){setError('Invalid member ID or password.');return}localStorage.setItem('tk_user_session',JSON.stringify({id:clean,name:data.name||clean}));location.reload()}catch{setError('Could not connect to the internal service. Check your Firebase environment variables.')}finally{setBusy(false)}}return <div className="form"><div className="eyebrow">Private access</div><h1>TongerKhobor</h1><p className="muted">Sign in to the internal newsroom workspace.</p><label className="field">Member ID<input id="id" className="input" autoComplete="username" placeholder="Your internal member ID"/></label><label className="field">Password<input id="password" className="input" type="password" autoComplete="current-password" placeholder="Your password" onKeyDown={e=>{if(e.key==='Enter')signIn()}}/></label><button className="btn primary" style={{width:'100%',marginTop:8}} onClick={signIn} disabled={busy}>{busy?<><Loader2 size={16} className="spin"/> Checking…</>:'Authenticate session'}</button>{error&&<div className="error">{error}</div>}<div className="notice">Internal portal • TongerKhobor team only</div></div>}
